install cbindgen

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -39,7 +39,7 @@ jobs:
           brew install \
             extra-cmake-modules \
             autoconf automake libtool autoconf-archive \
-            bison vala || true # ignore brew link python error
+            bison vala cbindgen || true # ignore brew link python error
           pip install -r requirements.txt
           echo /opt/homebrew/opt/bison/bin >> $GITHUB_PATH
           if [[ "${{ matrix.arch }}" == "x86_64" ]]; then
