reproducible tar (#9)

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -43,7 +43,15 @@ jobs:
             extra-cmake-modules \
             autoconf automake libtool autoconf-archive \
             byacc vala \
-            ninja meson || true # ignore brew link python error
+            ninja || true # ignore brew link python error
+          pip install meson==1.6.1
+
+      - name: Version info
+        run: |
+          bison --version
+          clang --version
+          cmake --version
+          valac --version
 
       - name: Build
         run: python scripts/build.py macos
@@ -55,9 +63,19 @@ jobs:
           path: |
             build/macos-${{ matrix.arch }}/*.tar.bz2
 
+      - name: Check absolute path
+        run: ./scripts/check-absolute-path.sh
+
       - name: Setup tmate session
         if: ${{ failure() }}
         uses: mxschmitt/action-tmate@v3
+
+  compare:
+    needs: build
+    if: ${{ github.ref != 'refs/heads/master' }}
+    uses: ./.github/workflows/compare.yml
+    with:
+      platform: macos
 
   release:
     needs: build
